import { StyleSheet } from 'react-native';

export const AIPALETTE = {
    primaryPurple: '#5F3DC4',
    lightPurpleInputBg: '#E1D5FF',
    veryLightPurpleButtonBg: '#F0EBFF',
    containerBg: '#FAF7FF',
    textInputPlaceholder: '#8071B3',
    textInputValue: '#4A2C9D',
    white: '#FFFFFF',
    iconColor: '#4A2C9D',
};

export const aiSectionStyles = StyleSheet.create({
    container: {
        backgroundColor: AIPALETTE.containerBg,
        borderRadius: 20,
        padding: 20,
        alignSelf: 'center',
        width: '90%',
        marginHorizontal: 16,
        marginVertical: 20,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 5,
        elevation: 4,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: AIPALETTE.primaryPurple,
        textAlign: 'center',
        marginBottom: 12,
        textTransform: 'uppercase',
    },
    learnMoreButton: {
        backgroundColor: AIPALETTE.primaryPurple,
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 20,
        alignSelf: 'center',
        marginBottom: 25,
    },
    learnMoreButtonText: {
        color: AIPALETTE.white,
        fontSize: 14,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: AIPALETTE.lightPurpleInputBg,
        borderRadius: 25,
        paddingHorizontal: 20,
        paddingVertical: 8,
        marginBottom: 20,
        minHeight: 50,
    },
    textInput: {
        flex: 1,
        fontSize: 16,
        color: AIPALETTE.textInputValue,
        paddingVertical: 8,
    },
    clearButton: {
        padding: 5,
        marginLeft: 8,
    },
    analyzeButton: {
        backgroundColor: AIPALETTE.veryLightPurpleButtonBg,
        paddingVertical: 14,
        paddingHorizontal: 30,
        borderRadius: 25,
        alignSelf: 'center',
    },
    analyzeButtonText: {
        color: AIPALETTE.primaryPurple,
        fontSize: 16,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    responseAreaWrapper: {
        marginTop: 25,
    },
    responseBox: {
        padding: 15,
        backgroundColor: AIPALETTE.white,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: AIPALETTE.lightPurpleInputBg,
        minHeight: 100,
    },
    responseText: {
        fontSize: 15,
        color: AIPALETTE.textInputValue,
        lineHeight: 22,
    },
    responseActionsContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginTop: 15,
        gap: 10,
    },
    responseActionButton: {
        backgroundColor: AIPALETTE.veryLightPurpleButtonBg,
        paddingVertical: 8,
        paddingHorizontal: 15,
        borderRadius: 20,
    },
    responseActionButtonText: {
        color: AIPALETTE.primaryPurple,
        fontSize: 13,
        fontWeight: '600',
    },
    loadingIndicatorContainer: {
        minHeight: 100,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: AIPALETTE.white,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: AIPALETTE.lightPurpleInputBg,
        padding: 15,
    },
    loadingText: {
        marginTop: 10,
        color: AIPALETTE.primaryPurple,
        fontSize: 14,
    }
});
